import { defineConfig, type Plugin } from "vitest/config";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

const staticPwaFiles = [
  "/",
  "/index.html",
  "/offline.html",
  "/manifest.webmanifest",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
] as const;

function pwaServiceWorker(): Plugin {
  return {
    name: "tiny-password-pwa-service-worker",
    apply: "build",
    generateBundle(_options, bundle) {
      const bundledAssets = Object.keys(bundle)
        .filter((fileName) => fileName.startsWith("assets/"))
        .sort()
        .map((fileName) => `/${fileName}`);
      const precache = [...staticPwaFiles, ...bundledAssets];
      this.emitFile({
        type: "asset",
        fileName: "sw.js",
        source: `/* Generated by Vite. This list is intentionally explicit. */
const CACHE_NAME = "tp-static-v1";
const PRECACHE_URLS = ${JSON.stringify(precache, null, 2)};
const PRECACHE = new Set(PRECACHE_URLS);

self.addEventListener("install", (event) => {
  // Deliberately wait for an explicit user action before taking control.
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) => Promise.all(names.filter((name) => name !== CACHE_NAME).map((name) => caches.delete(name))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("message", (event) => {
  if (event.data?.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Navigations, API calls, downloads, and every non-whitelisted URL remain
  // network-only. An offline navigation gets only the static explanation.
  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request).catch(() => caches.open(CACHE_NAME).then((cache) => cache.match("/offline.html"))),
    );
    return;
  }
  if (!PRECACHE.has(url.pathname) || url.search) return;

  event.respondWith(
    caches.open(CACHE_NAME).then((cache) => cache.match(request).then((cached) => cached ?? fetch(request))),
  );
});
`,
      });
    },
  };
}

// The build lands inside the Go module so `go:embed` picks it up.
// emptyOutDir stays false so the committed dist/.keep survives; stale hashed
// bundles are removed by the npm build script instead.
export default defineConfig({
  plugins: [react(), tailwindcss(), pwaServiceWorker()],
  build: {
    outDir: "../internal/webassets/dist",
    emptyOutDir: false,
  },
  server: {
    proxy: {
      "/api": "http://127.0.0.1:8080",
      "/healthz": "http://127.0.0.1:8080",
      "/readyz": "http://127.0.0.1:8080",
    },
  },
  test: {
    environment: "jsdom",
    setupFiles: "./vitest.setup.ts",
  },
});
